### PR TITLE
Update PKGBUILD

### PR DESCRIPTION
**Pull request by ZeroDot1**
It still does not work. 
Building Magic Fountain works, but the package is not complete.

## LOG:
```bash
$ makepkg -csi
==> Erstelle Paket: magicfountain 1.0.0-1 (Do 24. Aug 19:34:47 CEST 2017)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> 1.0.0-alpha4.tar.gz gefunden
==> Überprüfe source Dateien mit md5sums...
    1.0.0-alpha4.tar.gz ... Durchgelaufen
==> Entpacke Quellen...
  -> Entpacke 1.0.0-alpha4.tar.gz mit bsdtar
==> Beginne build()...
Info: creating stash file /home/user/magicfountain-bin/src/magicfountain-1.0.0-alpha4/.qmake.stash
/usr/bin/uic mainwindow.ui -o ui_mainwindow.h
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt/mkspecs/linux-g++ -o main.o main.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt/mkspecs/linux-g++ -o mainwindow.o mainwindow.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt/mkspecs/linux-g++ -o script.o script.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt/mkspecs/linux-g++ -o block.o block.cpp
/usr/bin/rcc -name ressources ressources.qrc -o qrc_ressources.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt/mkspecs/linux-g++ -o qrc_ressources.o qrc_ressources.cpp
g++ -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp
/usr/bin/moc -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB --include ./moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/user/magicfountain-bin/src/magicfountain-1.0.0-alpha4 -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/include-fixed -I/usr/include mainwindow.h -o moc_mainwindow.cpp
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt/mkspecs/linux-g++ -o moc_mainwindow.o moc_mainwindow.cpp
g++ -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o MagicFountain main.o mainwindow.o script.o block.o qrc_ressources.o moc_mainwindow.o   -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
==> Betrete fakeroot Umgebung...
==> Beginne package()...
make: Für das Ziel „install“ ist nichts zu tun.
==> Säubere Installation...
  -> Entferne libtool Dateien...
  -> Bereinige ungewollte Dateien...
  -> Entferne statische Bibliotheken...
  -> Entferne unnötige Symbole aus Binär-Dateien und Bibliotheken...
  -> Komprimiere Man-Pages und Info-Seiten...
==> Prüfe auf Paketierungsprobleme...
==> Erstelle Paket "magicfountain"...
  -> Erstelle .PKGINFO Datei...
  -> Erstelle .BUILDINFO Datei...
  -> Erstelle .MTREE-Datei...
  -> Komprimiere Paket... 
==> Verlasse fakeroot Umgebung.
==> Beendete Erstellung: magicfountain 1.0.0-1 (Do 24. Aug 19:35:01 CEST 2017)
==> Installiere Paket magicfountain mit pacman -U...
[sudo] Passwort für user: 
Lade Pakete...
Warnung: magicfountain-1.0.0-1 ist aktuell -- Reinstalliere
Löse Abhängigkeiten auf...
Suche nach in Konflikt stehenden Paketen...

Pakete (1) magicfountain-1.0.0-1

Gesamtgröße der installierten Pakete:  0,00 MiB
Größendifferenz der Aktualisierung:  0,00 MiB

:: Installation fortsetzen? [J/n] 
(1/1) Prüfe Schlüssel im Schlüsselring             [######################] 100%
(1/1) Überprüfe Paket-Integrität                   [######################] 100%
(1/1) Lade Paket-Dateien                           [######################] 100%
(1/1) Prüfe auf Dateikonflikte                     [######################] 100%
(1/1) Überprüfe verfügbaren Festplattenspeicher    [######################] 100%
:: Verarbeite Paketänderungen...
(1/1) Installiere magicfountain                    [######################] 100%
==> Räume auf...
```
```
# Generated by makepkg 5.0.2
# using fakeroot version 1.21
# Thu Aug 24 17:35:01 UTC 2017
pkgname = magicfountain
pkgver = 1.0.0-1
pkgdesc = A Fountain syntax editor and viewer.
url = https://github.com/Aztorius/magicfountain
builddate = 1503596101
packager = Unknown Packager
size = 4096
arch = x86_64
license = GPL3
depend = qt5-base
makedepend = qt5-base
makedepend = git
```

Screenshot: 
bildschirmfoto_2017-08-24_19-43-43

### CODE REVIEW

**Comment by Aztorius** [comment]
Yep. That's normal. We just have to copy the executable into an appropriate folder.
Add this into build().

`mkdir -p $pkgdir/usr/bin/`
`cp magicfountain $pkgdir/usr/bin/`
`chmod +x $pkgdir/usr/bin`

I'm not sure where the magicfountain elf file is created, so the second line may be different.

**Comment by Aztorius** [comment]
The LICENSE file can also be copied to $pkgdir/usr/share/licenses/magicfountain/

**Comment by ZeroDot1** [comment]
That does not work.
# PKGBUILD
```
md5sums=('4f7bda958f29a23fbfdd59980173a383')

build() {
	cd ${srcdir}/${pkgname}-${pkgver}-alpha4
	qmake-qt5 PREFIX='/usr' \
        LIBDIR='/usr/lib'
        make
	mkdir -p $pkgdir/usr/bin/
	cp magicfountain $pkgdir/usr/bin/
	chmod +x $pkgdir/usr/bin
	
}

package() {
	cd ${srcdir}/${pkgname}-${pkgver}-alpha4
	make DESTDIR="$pkgdir/" install
}
```
# Log:
```bash
$ makepkg -csi
==> Erstelle Paket: magicfountain 1.0.0-1 (Do 24. Aug 21:04:37 CEST 2017)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> 1.0.0-alpha4.tar.gz gefunden
==> Überprüfe source Dateien mit md5sums...
    1.0.0-alpha4.tar.gz ... Durchgelaufen
==> Entpacke Quellen...
  -> Entpacke 1.0.0-alpha4.tar.gz mit bsdtar
==> Entferne existierendes $pkgdir/ Verzeichnis...
==> Beginne build()...
make: Für das Ziel „first“ ist nichts zu tun.
mkdir: das Verzeichnis „/home/user/magicfountain-bin/pkg/magicfountain“ kann nicht angelegt werden: Keine Berechtigung
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...

```

**Comment by Aztorius** [comment]
And with
`cp magicfountain/magicfountain $pkgdir/usr/bin/`
?

**Comment by ZeroDot1** [comment]
That does not work.
```
namcap '/home/user/magicfountain-bin/magicfountain-1.0.0-1-x86_64.pkg.tar'
magicfountain W: No ELF files and not an "any" package

```

**Comment by ZeroDot1** [comment]
OK, let's do it later, I suggest that we put the first time on the TODO list.

**Comment by Aztorius** [comment]
I will test everything with Manjaro.

**Comment by Aztorius** [comment]
Fixed

**Pull request closed without merging**
