### PR TITLE
Update PKGBUILD

### PR DESCRIPTION
**Pull request by ZeroDot1**
I have now created folders and put the icon and the .desktop file into them.
See: https://github.com/Aztorius/magicfountain/pull/47/commits/8657b6b64dd32a9873c95c9f80076669bd4ae64f

### CODE REVIEW

**Comment by ZeroDot1** [comment]
Please create a new release in the next time.

**Comment by Aztorius** [comment]
Is the desktop icon and shortcut working ?

**Comment by ZeroDot1** [comment]
I haven't tested it,
With other applications, it works fine, see:  https://github.com/ColinDuquesnoy/MellowPlayer/tree/develop/share

**Comment by Aztorius** [comment]
It will not work with Arch packages because they are not copied to the right directory into $pkgdir.

**Comment by ZeroDot1** [comment]
Downlod .DEB https://drive.google.com/open?id=0BxK4dMpq7mr5YTQ0YVBRaUpzTFU
I tested it with Ubuntu. the entry Magic Fountain can now be found in the menu.
The reason why Archlinux doesn't work is that there is some kind of error in the PKGBUILD.
auswahl_001

**Comment by Aztorius** [comment]
Could you describe how do you build this DEB step by step ?

**Comment by ZeroDot1** [comment]
Okay, that's very simple.
```bash
sudo apt-get install checkinstall
```
A simple example that demonstrates the use of checkinstall.

```bash
tar xvf magicfountain-1.0.tar.gz
cd magicfountain-1.0
qmake
make
sudo checkinstall
```

**Comment by Aztorius** [comment]
Ok. I do it from scratch with dpkg (see in .travis.yml file).
I tried your .deb file, but no shortcut was created, which is a bit strange. Is there something else when you install it ?

**Pull request closed without merging**
